-- 敏捷估点服务数据库表结构
-- Agile Planning Poker Service Database Schema

-- 需求池表 (Backlog Pool Table)
CREATE TABLE IF NOT EXISTS backlog_pool (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1) PRIMARY KEY COMMENT '需求池唯一标识',
    name VARCHAR(100) NOT NULL COMMENT '需求池名称',
    description VARCHAR(500) COMMENT '需求池描述',
    created_by VARCHAR(20) COMMENT '创建者用户名（默认需求池为NULL，表示不归属任何人）',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间'
);

-- 故事卡表 (Story Card Table)
CREATE TABLE IF NOT EXISTS story_card (
    id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '故事卡唯一标识',
    title VARCHAR(100) NOT NULL COMMENT '故事卡标题',
    description VARCHAR(2000) COMMENT '故事卡描述',
    status VARCHAR(20) NOT NULL DEFAULT 'NOT_ESTIMATED' COMMENT '估点状态：NOT_ESTIMATED/ESTIMATING/ESTIMATED',
    story_point INTEGER COMMENT '估点结果（斐波那契数列，应用层验证）',
    created_by VARCHAR(20) NOT NULL COMMENT '创建者用户名',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    estimated_at TIMESTAMP COMMENT '估点完成时间',
    pool_id BIGINT NOT NULL COMMENT '所属需求池ID',
    host_name VARCHAR(20) NOT NULL COMMENT '主持人用户名（创建者）',
    voting_session_id BIGINT COMMENT '绑定的估点会话ID',
    FOREIGN KEY (pool_id) REFERENCES backlog_pool(id) ON DELETE CASCADE
);

-- 故事卡状态索引
CREATE INDEX IF NOT EXISTS idx_story_card_status ON story_card(status);

-- 估点会话表 (Voting Session Table)
-- 使用story_card_id作为主键，实现1:1关系
CREATE TABLE IF NOT EXISTS voting_session (
    story_card_id BIGINT PRIMARY KEY COMMENT '故事卡ID（作为会话ID）',
    status VARCHAR(20) NOT NULL DEFAULT 'IN_PROGRESS' COMMENT '会话状态：IN_PROGRESS/COMPLETED/CANCELLED',
    revealed_at TIMESTAMP COMMENT '结果揭示时间',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    completed_at TIMESTAMP COMMENT '完成时间',
    host_name VARCHAR(20) NOT NULL COMMENT '主持人用户名',
    voting_started_at TIMESTAMP COMMENT '开始投票时间',
    voting_deadline TIMESTAMP COMMENT '投票截止时间（开始后30秒）',
    FOREIGN KEY (story_card_id) REFERENCES story_card(id) ON DELETE CASCADE
);

-- 会话状态索引
CREATE INDEX IF NOT EXISTS idx_voting_session_status ON voting_session(status);

-- 投票表 (Vote Table)
CREATE TABLE IF NOT EXISTS vote (
    id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '投票唯一标识',
    story_card_id BIGINT NOT NULL COMMENT '故事卡ID（关联到会话）',
    participant_name VARCHAR(20) NOT NULL COMMENT '参与者用户名',
    story_point INTEGER NOT NULL COMMENT '故事点数（斐波那契数列，应用层验证）',
    voted_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '投票时间',
    FOREIGN KEY (story_card_id) REFERENCES voting_session(story_card_id) ON DELETE CASCADE,
    CONSTRAINT uk_vote_session_participant UNIQUE (story_card_id, participant_name)
);

-- 投票会话ID索引
CREATE INDEX IF NOT EXISTS idx_vote_session_id ON vote(story_card_id);

-- 参与者表 (Participant Table)
CREATE TABLE IF NOT EXISTS participant (
    id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '参与者记录唯一标识',
    story_card_id BIGINT NOT NULL COMMENT '故事卡ID（关联到会话）',
    participant_name VARCHAR(20) NOT NULL COMMENT '参与者用户名',
    joined_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '加入时间',
    FOREIGN KEY (story_card_id) REFERENCES voting_session(story_card_id) ON DELETE CASCADE,
    CONSTRAINT uk_participant_session_name UNIQUE (story_card_id, participant_name)
);

-- 参与者会话ID索引
CREATE INDEX IF NOT EXISTS idx_participant_session_id ON participant(story_card_id);

-- 故事点数验证说明
-- 注意：数据库层面不限制story_point的值，由应用层（StoryPoint值对象）负责验证
-- 应用层确保只有有效的斐波那契数（当前业务范围：1, 2, 3, 5, 8, 13）可以被存储

-- 会话状态CHECK约束
ALTER TABLE voting_session ADD CONSTRAINT IF NOT EXISTS chk_session_status 
    CHECK (status IN ('IN_PROGRESS', 'COMPLETED', 'CANCELLED'));

-- 故事卡状态CHECK约束
ALTER TABLE story_card ADD CONSTRAINT IF NOT EXISTS chk_card_status 
    CHECK (status IN ('NOT_ESTIMATED', 'ESTIMATING', 'ESTIMATED'));
